### ISSUE TITLE
Potential bugs in dealing with bridged rings

### ISSUE THREAD

**Issue by rosmarin** [UCLCheminformatics/ScaffoldGraph#5] opened 2020-06-14 06:57 UTC
When dealing with bridged rings using ScaffoldNetwork, the output is different from a similar structure with an aliphatic ring. Some nodes are just missing from the network.

**Comment by OliverBScott** [comment] 2020-06-15 07:33
Hi, could you please provide a specific example so I can reproduce the issue?

**Comment by rosmarin** [comment] 2020-06-15 07:46
For example, a molecule with smiles 'c3cccc(CC4CC5CCC4CC5)c3' will miss a node with the benzene.

**Comment by OliverBScott** [comment] 2020-06-15 09:33
Ah okay, so symmetric rings are a difficult case. In this case, the behavior you experience is expected. 

The scaffold network is an extension of the scaffold tree where instead of filtering the scaffolds generated through iterative removal, all of the scaffolds are retained. Removal of a ring means
that bonds and atoms which are part of the ring are removed excluding atoms and bonds which are part of any other ring. In the case of a symmetric ring all atoms belong to more than one ring, hence none can be removed. The algorithm will stop here because there are no possible ring combinations that are in the hierarchy below (3) so benzene in this molecule will not be produced due to it being a member of hierarchy 1. In the original scaffold tree [paper](https://pubs.acs.org/doi/10.1021/ci600338x) this snippet explains the behaviour:

> "In this set of K-rings, the symmetry of highly symmetric ring systems like adamantane is retained (the K-ring set contains, in this case, four six-membered rings, unlike three rings selected randomly as in the case of the smallest set of smallest rings; Scheme 2a). In such rare cases where highly symmetric rings are present, it is often not possible to remove only one ring at a time, because there are no atoms belonging only to one ring. In this situation, the algorithm stops at this stage and the ring system is not dissected further."

I cross-checked the result with Scaffold Network Generator (SNG) and the behaviour is identical.

I hope this makes sense?

**Comment by rosmarin** [comment] 2020-06-15 10:03
But for molecule like c3ccccc3CC4CCCCC4, it has similar symmetry but the benzene is maintained.

**Comment by OliverBScott** [comment] 2020-06-15 10:06
Yes this is true, but the SSSR for C1CCCCC1 is 1 and no atoms within the ring are members of multiple rings.

**Comment by rosmarin** [comment] 2020-06-15 10:13
I probably need to read the paper first. Thank you for your answering.

**Comment by OliverBScott** [comment] 2020-06-15 10:33
No problem. I think these particular rings are a difficult case and aren't too common. The way the algorithm functions at the moment is how I interpreted the paper and is identical to the other SN implementations I have tested. 

I will close this issue for now but if you have any further questions or comments feel free to open it again. I am happy to discuss anything :)

**Closed by OliverBScott** 2020-06-15 10:33 UTC
